stages:
  - package
  - deploy

variables:
  REPO_DIR: /ext/cluster/default/default/repository/helm

.package chart:
  stage: package
  image: registry.gitlab.com/promethistai/system/deployer
  variables:
    NAME: xxx
  only:
    refs:
      - tags
  script:
    - sed -i -- "s/chart.version/$CI_COMMIT_REF_NAME/g" $NAME/Chart.yaml
    - helm3 package $NAME
    - cp *.tgz $REPO_DIR

package chart admin:
  extends: '.package chart'
  variables:
    NAME: admin
  only:
    changes:
      - admin/**/*

package chart runner:
  extends: '.package chart'
  variables:
    NAME: runner
  only:
    changes:
      - runner/**/*

package chart builder:
  extends: '.package chart'
  variables:
    NAME: builder
  only:
    changes:
      - builder/**/*

package chart triton:
  extends: '.package chart'
  variables:
    NAME: triton
  only:
    changes:
      - triton/**/*

deploy charts:
  stage: deploy
  image: registry.gitlab.com/promethistai/system/deployer
  script:
    - helm3 repo index $REPO_DIR
