apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  tls:
    - hosts:
        - triton{{ if ne .Values.namespace "default" }}.{{ .Values.namespace }}{{ end }}.{{ .Values.basedomain }}
        - metrics.triton{{ if ne .Values.namespace "default" }}.{{ .Values.namespace }}{{ end }}.{{ .Values.basedomain }}
      secretName: {{ .Values.name }}-tls
  rules:
    - host: triton{{ if ne .Values.namespace "default" }}.{{ .Values.namespace }}{{ end }}.{{ .Values.basedomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 8000
    - host: grpc.triton{{ if ne .Values.namespace "default" }}.{{ .Values.namespace }}{{ end }}.{{ .Values.basedomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 8001
    - host: metrics.triton{{ if ne .Values.namespace "default" }}.{{ .Values.namespace }}{{ end }}.{{ .Values.basedomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 8002
